<?php
// fake API definition for the Exception class
return array(
    'summ' => "Base PHP exception class.",
    'narr' => "",
    'tech' => array(),
    'from' => array(),
    'properties' => array(
        'message' => array(
            'name'   => 'message',
            'summ'   => 'Exception message.',
            'narr'   => '',
            'tech'   => array(),
            'type'   => 'string',
            'access' => 'protected',
            'from'   => false,
        ),
        'code' => array(
            'name'   => 'code',
            'summ'   => 'User-defined exception code.',
            'narr'   => '',
            'tech'   => array(),
            'type'   => 'mixed',
            'access' => 'protected',
            'from'   => false,
        ),
        'file' => array(
            'name'   => 'file',
            'summ'   => 'Source filename of exception.',
            'narr'   => '',
            'tech'   => array(),
            'type'   => 'string',
            'access' => 'protected',
            'from'   => false,
        ),
        'line' => array(
            'name'   => 'line',
            'summ'   => 'Source line of exception.',
            'narr'   => '',
            'tech'   => array(),
            'type'   => 'int',
            'access' => 'protected',
            'from'   => false,
        ),
    ),
    'methods' => array(
        '__construct' => array(
            'name'   => '__construct',
            'summ'   => 'Constructor.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => false,
            'return' => null,
            'from'   => false,
            'params' => array(
                'message' => array(
                    'name'     => 'message',
                    'type'     => 'string',
                    'summ'     => 'Exception message.',
                    'byref'    => false,
                    'optional' => true,
                    'default'  => null,
                ),
                'code' => array(
                    'name'     => 'code',
                    'type'     => 'mixed',
                    'summ'     => 'Exception code.',
                    'byref'    => false,
                    'optional' => true,
                    'default'  => 0,
                ),
            ),
        ),
        'getMessage' => array(
            'name'   => 'getMessage',
            'summ'   => 'Gets the exception message.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'string',
            'from'   => false,
            'params' => array(),
        ),
        'getCode' => array(
            'name'   => 'getCode',
            'summ'   => 'Gets the exception code.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'mixed',
            'from'   => false,
            'params' => array(),
        ),
        'getFile' => array(
            'name'   => 'getFile',
            'summ'   => 'Gets the source file name.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'string',
            'from'   => false,
            'params' => array(),
        ),
        'getLine' => array(
            'name'   => 'getLine',
            'summ'   => 'Gets the source line.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'int',
            'from'   => false,
            'params' => array(),
        ),
        'getTrace' => array(
            'name'   => 'getTrace',
            'summ'   => 'Gets an array of the backtrace().',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'array',
            'from'   => false,
            'params' => array(),
        ),
        'getTraceAsString' => array(
            'name'   => 'getTraceAsString',
            'summ'   => 'Gets a formatted string of the backtrace().',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => true,
            'return' => 'string',
            'from'   => false,
            'params' => array(),
        ),
        '__toString' => array(
            'name'   => '__toString',
            'summ'   => 'Converts the exception to a string for output.',
            'narr'   => '',
            'tech'   => array(),
            'access' => 'public',
            'static' => false,
            'final'  => false,
            'return' => 'string',
            'from'   => false,
            'params' => array(),
        ),
    ),
);
?>